### ISSUE TITLE
PropertyGrid control is showing RegistrySettings::Encryption

### ISSUE THREAD

**Issue by AmenJlili** [SoftCircuits/WinSettings#2]
**Situation**: 
PropertyGrid is a great control to edit settings classes that inherit from RegistrySettings.

**Issue**: 
Property Encryption of the base class Registry is visible. This might confuse the end-user. See visual:
![image](https://user-images.githubusercontent.com/16106587/164107415-891a8ad6-b5c7-4153-b4ce-0532374aa742.png)

**Desired action**: 
It would be great if the RegisterySettings::Encryption is not visible on the PropertyGrid.

**Comment by SoftCircuits** [comment]
So how am I supposed to hide it?

**Comment by AmenJlili** [comment]
I think you will need to mark the Encryption property with [Browsable(false)]

**Comment by AmenJlili** [comment]
Check that pull request #3
